### ISSUE TITLE
Remove a hover effect or modify it

### ISSUE THREAD

**Issue by Khizarshah01** [Yashdon999/Resume-Generator#21]
I would like to either modify it or remove it entirely tab hover effect.
![Screenshot from 2023-04-04 11-34-02](https://user-images.githubusercontent.com/109973520/229704919-179b20f8-708a-4c8c-b63c-a42fe947454d.png)
you can see on this screenshot the work tab have a sky blue hover effect

**Comment by ShashwatAgrawal20** [comment]
I think modifying it would be a nice idea, as of now it looks incomplete as the top border is missing !

**Comment by munnokd** [comment]
Can I work on this issue?

**Comment by Pragyan14** [comment]
I want to work on this issue please assign me this issue.

**Comment by Khizarshah01** [comment]
You both can work on it and there are other issues you can participate in that too

**Comment by munnokd** [comment]
Thank you @Khizarshah01  for assign this issue

**Comment by Yashdon999** [comment]
@Pragyan14 have you started working on this issue? If not there is also another issue open I can assign you there.

**Comment by Pragyan14** [comment]
I am working on issue

**Comment by faisalamin001** [comment]
I am available to fix this issue

**Comment by Khizarshah01** [comment]
I had already assigned this issue to @munnokd but if you are able to resolve this issue fast then I will assign it to you also

**Comment by munnokd** [comment]
Hey @Khizarshah01 I made pr on this please check it. I solved this issue.

**Comment by Khizarshah01** [comment]
completed !
