### ISSUE TITLE
Enhancing User Experience: Add Homepage Style and Animations/Effects

### ISSUE THREAD

**Issue by Khizarshah01** [Yashdon999/Resume-Generator#22]
The only thing in our website to attract the user is the home page so I think it would be great to enhance the home page's style and add some animation or visual effects to make it more engaging and dynamic.
Here are some of the proposed changes:

Current home page looks like:-
![current_home](https://user-images.githubusercontent.com/104668751/230451477-c2b585ce-f608-4053-aa9e-837f984ab9ee.png)

* Use parallax scrolling to create a sense of depth and motion as the user scrolls down the page.
* Add some interactive elements, such as hover animations on images or buttons.
* Use CSS animations to create a smooth transition between sections on the page.
I believe these changes will improve the user experience and attract more visitors to the resume genrator project.

**Comment by PURUSHOTHAM-REDDY-N** [comment]
hi i would like to do this assign me

**Comment by Khizarshah01** [comment]
@PURUSHOTHAM-REDDY-N  sure go a head.

**Comment by Khizarshah01** [comment]
too late
