### ISSUE TITLE
Need help creating API for Contact Page

### ISSUE THREAD

**Issue by Khizarshah01** [Yashdon999/Resume-Generator#26]
We have a contact page on our website, but it is not currently connected to an API for submitting messages and inquiries. We are seeking assistance in creating an API that will allow users to successfully submit their information through the contact form.

**Comment by tanvirraihanislam** [comment]
Hi @Khizarshah01 , I would like to work on this issue.
Please let me know where and how we can start the discussion.

**Comment by ShashwatAgrawal20** [comment]
@tanvirraihanislam There are other issues open, you can work there.

**Comment by tanvirraihanislam** [comment]
Sure, @ShashwatAgrawal20

**Comment by tanvirraihanislam** [comment]
> @tanvirraihanislam There are other issues open, you can work there.

Sure, @ShashwatAgrawal20

**Comment by salauddinn** [comment]
i am interested work on this please provide more details on it @ShashwatAgrawal20

**Comment by ShashwatAgrawal20** [comment]
Sorry @salauddinn we are still in discussion about this task. You can work some other issues.
