### ISSUE TITLE
Hamburger menu closing 

### ISSUE THREAD

**Issue by 777Prabhjot** [Yashdon999/Resume-Generator#35]
In mobile screens after clicking on hamburger menu icon when the menu got open hamburger icon should be replaced with
X mark icon i think it would be more user friendly.

<img width="204" alt="Screenshot 2023-04-09 134657" src="https://user-images.githubusercontent.com/68184118/230762208-5d87be35-39a3-4694-ae56-a1e5e81581c2.png">

**I would love to work on this.**

**Comment by ShashwatAgrawal20** [comment]
@777Prabhjot go ahead. Good luck

**Comment by Khizarshah01** [comment]
Done
