### ISSUE TITLE
Style/Redesign Contact Page 

### ISSUE THREAD

**Issue by ShashwatAgrawal20** [Yashdon999/Resume-Generator#38]
The contact page don't goes with the home page. You can redesign the contact page completely or make it look good by some theme change or background change.

**Comment by salauddinn** [comment]
can u assign me this

**Comment by 1bhavyasingh1** [comment]
Can I work on this

**Comment by ShashwatAgrawal20** [comment]
@1bhavyasingh1 you can work on some other issues. I can assign you there

**Comment by 1bhavyasingh1** [comment]
@ShashwatAgrawal20 Alright

**Comment by Khizarshah01** [comment]
@1bhavyasingh1  if you want I can assign you on #41

**Comment by 1bhavyasingh1** [comment]
@Khizarshah01 Alright mate I'd like to try #41

**Comment by Yashdon999** [comment]
@1bhavyasingh1 can you leave a message there, in order for us to assign you

**Comment by salauddinn** [comment]
![Screenshot 2023-04-10 at 7 19 36 PM](https://user-images.githubusercontent.com/19387217/230914061-914ae7dc-7c56-4dab-9dcc-f951525d0ba3.png)

this design is okay for contact form @ShashwatAgrawal20  @Yashdon999

**Comment by salauddinn** [comment]
![Screenshot 2023-04-10 at 7 31 21 PM](https://user-images.githubusercontent.com/19387217/230916404-c9d87a34-3441-4c41-a8f7-82459e89eacb.png)
Please check this if this design is okay i will raise pr for the same @Yashdon999  @ShashwatAgrawal20

**Comment by ShashwatAgrawal20** [comment]
@salauddinn Looks a little too plain to me. Can you add some border or something, or create a PR.

**Comment by salauddinn** [comment]
Design 1
![Screenshot 2023-04-10 at 7 53 49 PM](https://user-images.githubusercontent.com/19387217/230920489-aebf04e9-05b7-4760-8cac-540f2b1e4caa.png)

 Design 2
![Screenshot 2023-04-10 at 7 54 21 PM](https://user-images.githubusercontent.com/19387217/230920598-0a64531d-ed23-49df-8ead-e51c1b34d5af.png)


@ShashwatAgrawal20  which one should we go ahead with?

**Comment by ShashwatAgrawal20** [comment]
@salauddinn are you still working on this ?

**Comment by chatbot-1** [comment]
Hello Shashwat, Assign me this issue.

**Comment by ShashwatAgrawal20** [comment]
@chatbot-1 you can checkout some other issues if you want @salauddinn is working on this and raised a PR too.
