### ISSUE TITLE
 Enhancing the Responsiveness of the Resume Editor and Preview for Different Screen Sizes

### ISSUE THREAD

**Issue by ShashwatAgrawal20** [Yashdon999/Resume-Generator#40]
Our open-source resume generator currently faces challenges in displaying the live preview and editor on screens with dimensions between 1220 and 768 ( you can check it using chrome-tools ). Some parts of preview resume hides, while the editor is not centered on screens smaller than 768 pixels. 

![image](https://user-images.githubusercontent.com/72117025/230778841-91750961-f873-462e-8335-44150a2ad931.png)

![image](https://user-images.githubusercontent.com/72117025/230778956-f0fdb4be-c11a-4d51-bc96-edb66e8d542f.png)

**Comment by rajat62** [comment]
Hey, I would like to contribute!

**Comment by 777Prabhjot** [comment]
@ShashwatAgrawal20 i would love to work on this

**Comment by ShashwatAgrawal20** [comment]
@777Prabhjot sure, go ahead 😃
