### ISSUE TITLE
implement animate on scroll using aos package

### ISSUE THREAD

**Issue by PURUSHOTHAM-REDDY-N** [Yashdon999/Resume-Generator#48]
it will be awesome if we can add beautiful on scroll animations to the home page . i can add those scroll animations , assaign it to me.

**Comment by ShashwatAgrawal20** [comment]
@PURUSHOTHAM-REDDY-N Appreciate it man, but **aos** is **dead** what about something like **framer-motion**. 

And we already have an issue open #22 related to this. So message there so that we can assign you
