### ISSUE TITLE
Contact form validation

### ISSUE THREAD

**Issue by 777Prabhjot** [Yashdon999/Resume-Generator#54]
Contact form getting submitted even without filling any fields inside inputs, validation is required for all the fields
so that it don't submit empty data.

**To Reproduce**

1. Go to 'Contact'
2. Click on 'Send Message'

https://user-images.githubusercontent.com/68184118/231346284-e328939f-c0d0-4240-b0e3-60bb96a8bc59.mp4

**Comment by ShashwatAgrawal20** [comment]
@777Prabhjot  We appreciate your feedback and would like to clarify that the current page design is not functional and does not send any data. It was added as a placeholder for future implementation, and we are still in the process of deciding on the most suitable backend solution.

We welcome any suggestions you may have regarding the backend solution.

**Comment by Khizarshah01** [comment]
we are still in the process of deciding on the most suitable back-end solution.
