### ISSUE TITLE
Redesign Footer 

### ISSUE THREAD

**Issue by Khizarshah01** [Yashdon999/Resume-Generator#59]
the footer is an important part of the website, we would like to request a new and more attractive design for it.

**Comment by shyamtawli** [comment]
Hey @Khizarshah01 do you have a design for it? I can work on development part if you have any design you want to be build.

**Comment by TJRelly** [comment]
What important information would you like to include in your footer?

**Comment by Khizarshah01** [comment]
@TJRelly @shyamtawli we don't have a specific design in mind for the footer at this time.

We would appreciate it if you could use your best judgment to create a footer that is visually appealing and consistent with the overall design of the website. Please keep in mind the following elements that we would like to include:

1. A copyright notice, including the year the website was created or last updated.
2. A link to our website's contact page.
3. A link to our website's about page.

If you have any questions or need any additional resources to complete the task, please let us know. We appreciate your help in improving our website!
