### ISSUE TITLE
There should be delete option for education section also

### ISSUE THREAD

**Issue by 777Prabhjot** [Yashdon999/Resume-Generator#67]
**Describe the bug**
In the resume page education section should also have delete functionality so the user can delete the added degree section in case they don't need it.

**Screenshots**
<img width="958" alt="Screenshot 2023-04-27 163126" src="https://user-images.githubusercontent.com/68184118/234845074-ed8c96e9-60cf-4023-b2e8-0651a2f9a909.png">
<img width="943" alt="Screenshot 2023-04-27 163153" src="https://user-images.githubusercontent.com/68184118/234845112-38a68285-3555-44e0-a236-2170aeb11665.png">

**Additional context**

**Comment by ShashwatAgrawal20** [comment]
sure @777Prabhjot go ahead. 

For reference checkout the **work tab**

Another issue in the Resume:- 
![image](https://user-images.githubusercontent.com/72117025/234911432-c38fa54b-3ee2-408f-ad36-27c0d6ac475e.png)
I think this shouldn't be there after deleting the **work tab**. pinging @Khizarshah01 @Yashdon999 for thoughts.

It would be great if you can work on this too. Let us confirm and let you know whether we have to remove it or show I am a complete fresher. 

Till then you can work on the **Education section**.

**Comment by 777Prabhjot** [comment]
@ShashwatAgrawal20  it's done
