### ISSUE TITLE
Screen is getting blanked while uploading image

### ISSUE THREAD

**Issue by 777Prabhjot** [Yashdon999/Resume-Generator#68]
**Describe the bug**
In resume page if we try to upload different documents or videos rather then images screen is getting blanked so i think it should display an error message like only jpg,jpeg,png are allowed something like that.

**Screenshots**

https://user-images.githubusercontent.com/68184118/234846101-17f4abba-b934-4a53-9376-b8119a333eb3.mp4

**Additional context**

**Comment by ShashwatAgrawal20** [comment]
@Khizarshah01 can you check?

**Comment by Khizarshah01** [comment]
@777Prabhjot  Thanks for find bug i will assigning you if you interested to work on it.

**Comment by 777Prabhjot** [comment]
@Khizarshah01 it's done please do check it out

**Comment by ShashwatAgrawal20** [comment]
@777Prabhjot have you created a PR?

**Comment by 777Prabhjot** [comment]
@ShashwatAgrawal20 yes
