### ISSUE TITLE
Github and portfolio links are missing only linkedin link is there . It will be really great if user can show there github and portfolio

### ISSUE THREAD

**Issue by hrutik7** [Yashdon999/Resume-Generator#77]

**Comment by debasish-dutta** [comment]
I can try to work on this issue.

**Comment by hrutik7** [comment]
need to discuss with repo maintainers

**Comment by Khizarshah01** [comment]
sorry for the late reply . if you interested to work on this issue leave comment "interested" i will assign you this issue.

**Comment by hrutik7** [comment]
hey @Khizarshah01 I am busy in some other stuff if the PR is raised for this issue then kindly close this issue :)

**Comment by debasish-dutta** [comment]
Yes, I am interested.
@Khizarshah01

**Comment by Khizarshah01** [comment]
@debasish-dutta go ahead

**Comment by debasish-dutta** [comment]
I'll do this by the end of the month

**Comment by debasish-dutta** [comment]
@Khizarshah01 do check the pull
