### ISSUE TITLE
Feat : Navbar enhancements 

### ISSUE THREAD

**Issue by shobhitexe** [Yashdon999/Resume-Generator#80]
Hey i guess the navbar can look more good if we add little padding and move this part to center 

![image](https://github.com/Yashdon999/Resume-Generator/assets/29349136/79e0e6f3-8fea-48d4-a6b3-160ac2b7d702)

lemme know if yes then you can assign this to me

**Comment by Khizarshah01** [comment]
@shobhitexe  if you want to work on this issue go ahead.

**Comment by shobhitexe** [comment]
> 
> ![Screenshot from 2023-05-31 20-43-57](https://github.com/Yashdon999/Resume-Generator/assets/109973520/ab520fc4-aafb-4839-b045-109d4d9b9118)
> Hey brother @shobhitexe there is another problem. When we open a website in mobile, there is a navbar option in the middle. can you fix it !

Sure 👍 like you want all links "Home" ,  "About" And all to be left side ?

**Comment by Khizarshah01** [comment]
leave it @shobhitexe , it's looking good and thank you for your contribution.
